name: "Build & Publish"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  emanote:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build the website (Nix) 🔧
        run: |
          nix build
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/
